# Generated by Django 3.2.5 on 2021-08-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusesWithComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_who_received', models.TextField()),
                ('username_who_sent', models.TextField()),
                ('bonus', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('bonus_admin', models.IntegerField()),
                ('bonus_colleague', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('first_name', models.TextField()),
                ('real_name_who_sent', models.TextField()),
                ('receiving_bonuses', models.BooleanField()),
                ('avatar', models.URLField()),
            ],
        ),
    ]
