# Generated by Django 3.2.5 on 2021-08-19 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonuseswithcomments',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonuseswithcomments',
            name='real_name_who_received',
            field=models.TextField(default='kk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bonuseswithcomments',
            name='real_name_who_sent',
            field=models.TextField(default='kk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='Access',
            field=models.BooleanField(default=False),
        ),
    ]
