# Generated by Django 3.2.5 on 2021-08-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letstart', '0002_auto_20210819_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftForBonuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.TextField()),
                ('start_time', models.TextField()),
                ('end_time', models.TextField()),
                ('accrued_bonuses', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='receivedbonuses',
            name='receiving_bonuses',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
